# CMake generated Testfile for 
# Source directory: /root/Downloads/cmake-3.10.2/Tests/FindGTK2
# Build directory: /root/Downloads/cmake-3.10.2/Tests/FindGTK2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GTK2Components.gtk "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gtk" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Components/gtk" "--build-generator" "Unix Makefiles" "--build-target" "gtk-all-libs" "--build-project" "gtk" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Components/gtk" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.glib "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/glib" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/glib" "--build-generator" "Unix Makefiles" "--build-project" "glib" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/glib" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gobject "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gobject" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gobject" "--build-generator" "Unix Makefiles" "--build-project" "gobject" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gobject" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gio "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gio" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gio" "--build-generator" "Unix Makefiles" "--build-project" "gio" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gio" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gmodule "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gmodule" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gmodule" "--build-generator" "Unix Makefiles" "--build-project" "gmodule" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gmodule" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gthread "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gthread" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gthread" "--build-generator" "Unix Makefiles" "--build-project" "gthread" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gthread" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.atk "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/atk" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/atk" "--build-generator" "Unix Makefiles" "--build-project" "atk" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/atk" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk_pixbuf "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gdk_pixbuf" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--build-generator" "Unix Makefiles" "--build-project" "gdk_pixbuf" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.cairo "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/cairo" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/cairo" "--build-generator" "Unix Makefiles" "--build-project" "cairo" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/cairo" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.pango "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/pango" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pango" "--build-generator" "Unix Makefiles" "--build-project" "pango" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pango" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.pangocairo "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/pangocairo" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--build-generator" "Unix Makefiles" "--build-project" "pangocairo" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoxft "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/pangoxft" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--build-generator" "Unix Makefiles" "--build-project" "pangoxft" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoft2 "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/pangoft2" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--build-generator" "Unix Makefiles" "--build-project" "pangoft2" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gdk" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gdk" "--build-generator" "Unix Makefiles" "--build-project" "gdk" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gdk" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
add_test(GTK2Targets.gtk "/root/Downloads/cmake-3.10.2/bin/ctest" "--build-and-test" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/gtk" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gtk" "--build-generator" "Unix Makefiles" "--build-project" "gtk" "--build-exe-dir" "/root/Downloads/cmake-3.10.2/Tests/FindGTK2/GTK2Targets/gtk" "--force-new-ctest-process" "--test-command" "/root/Downloads/cmake-3.10.2/bin/ctest" "-V")
